### ISSUE TITLE
ERROR: No matching distribution found for numpy==1.20.3

### ISSUE THREAD

**Issue by thinkwithas** [ninjakx/youtube-video2ppt#3]
When I run the code "pip install -r requirements.txt" ?
Can someone helps me ?

**Comment by ninjakx** [comment]
Which python version are you using?

**Comment by ninjakx** [comment]
Run `cat requirements.txt | xargs -n 1 pip install`  <---- this will skip the package where it fails.
In your case it will skip numpy because it's not able to find the version.

and then install the latest version of the packages separately by `pip install -U <pkg>`
e.g: 
`pip install -U numpy`    
I don't know the python or pip version you are using. So you can try this out and check if it works for you.

**Comment by thinkwithas** [comment]
Thanks!!!
The version of my python is latest "version 3.10.1", and pip version is "21.2.4".
With your help, I have installed the packages involved in  requirements.txt. However, this happened: 
![无标题](https://user-images.githubusercontent.com/94438383/146643148-914b050d-d362-439f-80cb-1746846d49fb.png)

**Comment by thinkwithas** [comment]
Sorry, I found my numpy installation still failed. Maybe it leads to the error above.

 ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the 'D:\Python3.10.1\python.exe -m pip install --upgrade pip' command.

**Comment by thinkwithas** [comment]
Sorry, I found my numpy installation still failed. 

error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
--------------------------------------------------------------------------------------
ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the 'D:\Python3.10.1\python.exe -m pip install --upgrade pip' command.

Is Microsoft Visual C++ 14.0 required? I already install VScode.

**Comment by thinkwithas** [comment]
sorry, I found my installation of numpy still failed. My python version is "3.10.1", pip version is "21.3.1".

  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the 'D:\Python3.10.1\python.exe -m pip install --upgrade pip' command.

Is Microsoft Visual C++ 14.0 required? I already installed VSCode. 
Thanks for your help !!!

**Comment by ninjakx** [comment]
I saw your last screenshot and the error in screenshot was due to restriction placed by your country. Is your location china? for that issue `
Unable to download webpage: <urlopen error [WinError 10060]` 
see this : https://github.com/ytdl-org/youtube-dl/issues/12537

I have tested the script on python 3.6 so can't say anything about the python 3.10.
Try this: https://stackoverflow.com/questions/29846087/microsoft-visual-c-14-0-is-required-unable-to-find-vcvarsall-bat

**Comment by ninjakx** [comment]
can you try this?
```
pip install pipwin 
pipwin install yourLibrary
```

**Comment by thinkwithas** [comment]
I reinstalled python with the version "3.6" and successfully installed all packages required.

Yes, I am in China. 
Firstly, I tried to skip the restriction by using proxy, but failed. I don't know if here is any mistakes?
![f4a7ad9b02a10b887ec1cc77ccf13a0](https://user-images.githubusercontent.com/94438383/146665411-44ff03af-2dcb-463d-9fc5-b353f0d439de.png)

I also tried to skip the restriction by using vpn, but failed.
![1639891354(1)](https://user-images.githubusercontent.com/94438383/146664910-04781521-5913-46dd-8042-6cc4038d5613.jpg)

what a big hassle. Thanks for your help anyway!

**Comment by thinkwithas** [comment]
It's weird that when I used vpn to skip the restriction and use the url mentioned in the demo. Webpage successfully downloaded, but there is another error.
![image](https://user-images.githubusercontent.com/94438383/146789231-4ada77eb-b7d4-4e18-851b-c90469eb6406.png)
...
 File "D:\Python3.10.1\lib\zipfile.py", line 721, in write
    n = self.fp.write(data)
AttributeError: 'WindowsPath' object has no attribute 'write'

**Comment by thinkwithas** [comment]
Could you do me a favor?

**Comment by ninjakx** [comment]
Regarding the url thing : can you share your original link? I think that link is because you are having t=64s part (time part)
Try removing that part.

for second thing: you are using Python3.10.1 I wrote the code in python3.6 so I think it's due to version. some thing are not getting supported in 3.10

**Comment by thinkwithas** [comment]
hooray!!! It worked.
I reinstalled python with version 3.6.2, and modified numpy==1.20.3 to numpy==1.19.3 in requirements.txt.
Thank you very much!

**Comment by ninjakx** [comment]
Glad it worked :) I tested it on friend's windows OS laptop with python 3.10. 
By removing the versions from requirements.txt it worked on his laptop.
So I guess the issue is related to the version of other modules mentioned in the requirements.txt.
